# Generated by Django 5.1.1 on 2025-03-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell_medicine_details',
            name='sell_medicine_bill_day',
        ),
        migrations.AddField(
            model_name='sell_medicine_bills',
            name='sell_medicine_bill_day',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
