# Generated by Django 5.1.1 on 2025-03-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Management', '0002_remove_sell_medicine_details_sell_medicine_bill_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_medicine_details',
            name='sell_medicine_amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sell_medicine_details',
            name='sell_meicine_id',
            field=models.CharField(max_length=50),
        ),
    ]
