# Generated by Django 5.1.1 on 2025-03-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Management', '0003_alter_sell_medicine_details_sell_medicine_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_medicine_data',
            name='purchase_medicine_QTY',
            field=models.IntegerField(),
        ),
    ]
