# Generated by Django 5.1.1 on 2025-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Management', '0005_sell_medicine_bills_sell_medicine_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_medicine_details',
            name='sell_medicine_quantity',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
