# Generated by Django 5.1.1 on 2025-03-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_Management', '0006_sell_medicine_details_sell_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_medicine_bills',
            name='sell_medicine_bill_Dr',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell_medicine_bills',
            name='sell_medicine_bill_patient',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
